spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/myproject
    username: kt
    password: 1234
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibarnate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000

server:
  port: 8080
  tomcat:
    threads:
      max: 30

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace